### ISSUE TITLE
Normalize grades before submitting to Stellar

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lmod_proxy#35]
As an instructor, I would like to have grades submitted to the lmod gradebook be "out of" the max score for the assignment. Grades coming from edX are between 0 and 1.0 and it would be clearer for instructors and students to have them be between 0 and the max score. 

- [ ] add a configuration setting to control whether grades should be normalized at all. In our current use of lmod-proxy this would be an application setting, similar to `LMODP_APPROVE_GRADES`
- [ ] fetch the max scores for all problems in the gradebook (possibly using [`get_assignments()`](http://pylmod.readthedocs.org/en/release/api.html#pylmod.gradebook.GradeBook.get_assignments)
- [ ] normalize the grades coming in from edX before submitting them in [L32-L35](https://github.com/mitodl/lmod_proxy/blob/master/lmod_proxy/edx_grades/actions.py#L32-L35)

This may be very slow and we'll need to consider the possibility of timeouts.

**Comment by pwilkins** [comment]
Location of obscure documentation:
1. On the edx-platform, there is a description of the "remote gradebook" API: /Users/pwilkins/projects/edx-cypress/devstack/edx-platform/docs/en_us/internal/remote_gradebook.md
2. The LMod API documentation doesn't describe what the attributes.  The user doc for LMod may help with that: https://wikis.mit.edu/confluence/display/LMODHelp/Gradebook

**Comment by pdpinch** [comment]
@ShawnMilo I saw you made a start in https://github.com/mitodl/PyLmod/pull/51

Can you tell me why you decided to make the changes to PyLmod instead of here?

**Comment by ShawnMilo** [comment]
@pdpinch:

My reasoning (and understanding) are as follows. Please feel free to correct any errors.

----

# PyLmod deals with data, lmod_proxy deals with authentication

lmod_proxy is a pass-through between PyLmod and learning-modules. It does not contain any logic which manipulates any data. It is primarily concerned with the difference in authentication schemes between edX and learning-modules. Specifically, learning-modules accepts authentication at an application level, as opposed to edX, where authentication is at a user level.

----

# PyLmod manipulates data in its code and its tests

PyLmod contains all the logic already for manipulating data (CSV to Python objects, for example), and already contains tests which have sample assignment, student, and grade data, and checks for expected values in its test suite.

# lmod_proxy deals with no data, only connections and authentication

lmod_proxy's tests are concerned with validating authentication input, making connections, checking for retry limits, and asserting the correct status codes are returned.

----

Based on those observations, the clear place to add this change is in PyLmod, not lmod_proxy.

cc @pwilkins, since he asked pretty much the same thing.

**Comment by pwilkins** [comment]
Upon reviewing user requirements, the description of this issue has changed.  The change is that the source of the normalization scaling factor is not Stellar, but edX.  It turns out that course staff want to use edX to weight and scale grades, as presented by the LMS Progress tab. 

In a nutshell, we intend to identify a source of the grade data, use that source to modify `get_student_grade_summary_data()`[1] in `legacy.py` which is called by `return_csv()`[2] in the same file.
 
## 1. Source of grade data
The `edx-submissions` repo contains `api.py`, which contains a `get_scores(course_id, student_id)` function which returns a dict. The key is the assignment ID, and the value is a tuple containing earned points and possible points. This function is called from two places in `lms/djangoapps/courseware/grades.py` to get grades.

## 2. Modify the the code that populates the remote gradebook CSV
In `legacy.py`, modify the content of the `datatable` that is passed to `return_csv()`.

[1] https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/legacy.py#L684
[2] https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/legacy.py#L129
[3] https://github.com/edx/edx-platform/blob/master/lms/djangoapps/instructor/views/legacy.py#L271

**Comment by pdpinch** [comment]
Thanks for the analysis. It looks good, but I have a question about transitions. When we make this change, everyone's grade exports will switch from being normalized (0 to 1) to being scaled. Should we do some research before making this change, or should we make it user-configurable?

**Comment by pwilkins** [comment]
Probably both, but I don't think users will mind.  The numbers we are passing currently require editing before they're useful, right?.  I would be surprised to find someone who didn't like the change.  Definitely do research, though.

It goes without saying that the PR would be more complex if we needed a UI change.

**Comment by pwilkins** [comment]
There may be a problem with our plan.  We were planning to use edx-submissions, but it may not return all the grades we want.

**Comment by pdpinch** [comment]
Can you say more about how you plan to use edx-submissions? It is not tied to ORA2, but as far as I know, only ORA2 and SGA use it reliably.

**Comment by pdpinch** [comment]
Moved this issue to https://github.com/mitocw/edx-platform/issues/95
